### ISSUE TITLE
Project name as run folder in report

### ISSUE THREAD

**Issue by jethror1** [eastgenomics/eggd_multiqc#12]
Following line is present at top of every report:

Report generated on 2020-06-28, 06:59 based on data in: /home/dnanexus/inp

Would be good to set the path to be the project name variable as this links the report to the run.

**Comment by sophie22** [comment]
header.html https://github.com/ewels/MultiQC/blob/master/multiqc/templates/default/header.html line 70
https://github.com/ewels/MultiQC/blob/master/multiqc/multiqc.py line 206, then 353
analysis_dir is an input to run_cli defined in multiqc.py but I'm not clear on where is it passed in
