### ISSUE TITLE
Warning samples not visible next to the title

### ISSUE THREAD

**Issue by Yu-jinKim** [eastgenomics/eggd_multiqc#17]
In QC of run 278, there is not a box to indicate the warning samples like the one for pass samples: 
![image](https://user-images.githubusercontent.com/25991776/93861247-18e40480-fcb8-11ea-863c-abf096465d3d.png)

The size of the box is proportional to the amount of samples "in" the box (you can see a little red for the 2 samples that failed):
![image](https://user-images.githubusercontent.com/25991776/93862794-83963f80-fcba-11ea-8e02-b31b393568c9.png)

**Comment by sophie22** [comment]
I see a tiny yellow line for the 1 warn sample in the first image you sent. It is not something I have control over. If important, it should be raised with the [MultiQC tool](https://github.com/ewels/MultiQC)
