### ISSUE TITLE
GC coverage plot Y axis not scaling

### ISSUE THREAD

**Issue by mattgarner** [eastgenomics/eggd_multiqc#26]
The y axis on the GC coverage plot does not scale with the data and is truncating the top of the plot

![image](https://user-images.githubusercontent.com/8166553/136925155-e37224f1-289d-4e03-9c56-e149078cdba8.png)

**Comment by Aisha-D** [comment]
@mattgarner Finiding a ymax limit is difficult. We can control up to what the y max is, by default it is 20 https://github.com/ewels/MultiQC/blob/master/multiqc/modules/picard/GcBiasMetrics.py#L100, but the peak is greater than 100
![Screenshot from 2022-07-01 13-34-42](https://user-images.githubusercontent.com/45298626/176896082-c8e4bf6f-017f-45b2-b143-bbaf12be8120.png)

Not sure whether to leave it at 40 (this is for haemonc data)

**Comment by Addy81** [comment]
This is controlled in the config has been adjusted in TWE https://github.com/eastgenomics/eggd_MultiQC_configs/pull/4 and CEN https://github.com/eastgenomics/eggd_MultiQC_configs/pull/2 and MYE https://github.com/eastgenomics/eggd_001_Reference/pull/157.
