### ISSUE TITLE
Out of memory for S2 flowcell

### ISSUE THREAD

**Issue by Yu-jinKim** [eastgenomics/eggd_multiqc#29]
The default instance type might not be enough 
 RAM-wise: https://platform.dnanexus.com/projects/G6Jf4gQ4z2f181P17jB4B892/monitor/job/G6Jjq304z2f4BxzxFFvQ6PFZ

**Comment by sophie22** [comment]
To my understanding it is only a problem (currently) for Twist WES. Instance type can be specified when running the app, ie in dias_batch_running for the `-a TWE` option.

**Comment by Yu-jinKim** [comment]
This actually got fixed in dias_batch_running, we can close this issue
