### ISSUE TITLE
Correct the location of the multiQC docker

### ISSUE THREAD

**Issue by Aisha-D** [eastgenomics/eggd_multiqc#35]
- MultiQC docker points to dev project so needs to be CAPA'd to be in 001_ref. 
- A more recent version of multiQC is available https://github.com/ewels/MultiQC/releases/tag/v1.12

**Comment by sophie22** [comment]
All pipelines now use the SE GLH modified version of the MultiQC Docker based on version v1.11 which is fully documented, verified for use and placed into 001_Reference in DNAnexus
