### ISSUE TITLE
Output_dir check does not work if no /output/ dir is present

### ISSUE THREAD

**Issue by chrispyatt** [eastgenomics/eggd_multiqc#36]
Providing a $primary option where there is no /output/ directory causes this to error out, rather than moving to the if statement:

```
# Check that an /output/ folder exists in the root of the project
            output_dir=$(dx ls --folders --brief  "$project:/output/")
            if [[ $output_dir ]]; then
                workflowdir="$project:/output/$primary"
            else
                workflowdir="$project:/$primary"
            fi
```
Example job (for B38 testing - hence the lack of normal directory structure): https://platform.dnanexus.com/projects/G9FKYPQ4kBX36YFX155g2v39/monitor/job/GJk64284kBXF4ff7205PYQ45

**Comment by jethror1** [comment]
using `dx find data "$project:/output/"` instead would fix this
